apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  replicas: 3
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - image: ghost
        name: ghost
        ports:
        - containerPort: 2368
          name: ghost
        volumeMounts:
        - name: ghost-persistent-storage
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-persistent-storage
        persistentVolumeClaim:
          claimName: ghost-pv-claim